package App;


import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class Quiz_Reg_Form extends javax.swing.JFrame {

    /**
     * Creates new form Quiz_Reg_Form
     */
    public Quiz_Reg_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bodyPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        namePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        sexPanel = new javax.swing.JPanel();
        sexLabel = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        notToSay = new javax.swing.JRadioButton();
        dobPanel = new javax.swing.JPanel();
        dobLabel = new javax.swing.JLabel();
        dobField = new javax.swing.JTextField();
        agePanel = new javax.swing.JPanel();
        ageLabel = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        addressPanel = new javax.swing.JPanel();
        countryLabel = new javax.swing.JLabel();
        addressPane = new javax.swing.JScrollPane();
        addressArea = new javax.swing.JTextArea();
        usernamePanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        useridField = new javax.swing.JTextField();
        passwordPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        passw = new javax.swing.JPasswordField();
        confirmPwdPanel = new javax.swing.JPanel();
        confirmPwdLabel = new javax.swing.JLabel();
        cpassw = new javax.swing.JPasswordField();
        schoolPanel = new javax.swing.JPanel();
        countryLabel1 = new javax.swing.JLabel();
        school = new javax.swing.JTextField();
        boardPanel = new javax.swing.JPanel();
        countryLabel2 = new javax.swing.JLabel();
        board = new javax.swing.JTextField();
        btnPanel = new javax.swing.JPanel();
        signUpBtn = new javax.swing.JPanel();
        signUpLabel = new javax.swing.JLabel();
        optionPanel = new javax.swing.JPanel();
        loginPrompt = new javax.swing.JLabel();
        r2loginBtn = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        Disclaimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Page");
        setBounds(new java.awt.Rectangle(400, 150, 0, 0));
        setResizable(false);

        bodyPanel.setBackground(new java.awt.Color(34, 43, 53));
        bodyPanel.setForeground(new java.awt.Color(242, 242, 242));

        titlePanel.setBackground(new java.awt.Color(34, 43, 53));
        titlePanel.setForeground(new java.awt.Color(242, 242, 242));

        titleLabel.setBackground(new java.awt.Color(60, 63, 66));
        titleLabel.setFont(new java.awt.Font("Myanmar Text", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(242, 242, 242));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("QuizApp");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addContainerGap())
        );

        inputPanel.setBackground(new java.awt.Color(34, 43, 53));
        inputPanel.setForeground(new java.awt.Color(242, 242, 242));
        inputPanel.setMaximumSize(new java.awt.Dimension(511, 423));
        inputPanel.setMinimumSize(new java.awt.Dimension(511, 423));
        inputPanel.setLayout(new java.awt.GridLayout(0, 1));

        namePanel.setBackground(new java.awt.Color(34, 43, 53));
        namePanel.setForeground(new java.awt.Color(242, 242, 242));

        nameLabel.setBackground(new java.awt.Color(60, 63, 66));
        nameLabel.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(242, 242, 242));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLabel.setText("  Name:");

        nameField.setBackground(new java.awt.Color(72, 75, 80));
        nameField.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        nameField.setForeground(new java.awt.Color(242, 242, 242));
        nameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        inputPanel.add(namePanel);

        sexPanel.setBackground(new java.awt.Color(34, 43, 53));
        sexPanel.setForeground(new java.awt.Color(242, 242, 242));

        sexLabel.setBackground(new java.awt.Color(60, 63, 66));
        sexLabel.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        sexLabel.setForeground(new java.awt.Color(242, 242, 242));
        sexLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sexLabel.setText("  Sex:");

        male.setBackground(new java.awt.Color(34, 43, 53));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        male.setForeground(new java.awt.Color(242, 242, 242));
        male.setSelected(true);
        male.setText("Male");
        male.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        male.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setBackground(new java.awt.Color(34, 43, 53));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        female.setForeground(new java.awt.Color(242, 242, 242));
        female.setText("Female");
        female.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        female.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        notToSay.setBackground(new java.awt.Color(34, 43, 53));
        buttonGroup1.add(notToSay);
        notToSay.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        notToSay.setForeground(new java.awt.Color(242, 242, 242));
        notToSay.setText("Prefer not to say");
        notToSay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        notToSay.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        notToSay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notToSayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sexPanelLayout = new javax.swing.GroupLayout(sexPanel);
        sexPanel.setLayout(sexPanelLayout);
        sexPanelLayout.setHorizontalGroup(
            sexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sexPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(female, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notToSay, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        sexPanelLayout.setVerticalGroup(
            sexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sexPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(sexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(notToSay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(female, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sexLabel)
                    .addComponent(male, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputPanel.add(sexPanel);

        dobPanel.setBackground(new java.awt.Color(34, 43, 53));
        dobPanel.setForeground(new java.awt.Color(242, 242, 242));

        dobLabel.setBackground(new java.awt.Color(60, 63, 66));
        dobLabel.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        dobLabel.setForeground(new java.awt.Color(242, 242, 242));
        dobLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dobLabel.setText("  Date of Birth:");

        dobField.setBackground(new java.awt.Color(72, 75, 80));
        dobField.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        dobField.setForeground(new java.awt.Color(242, 242, 242));
        dobField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dobField.setText("YYYY-MM-DD");
        dobField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dobPanelLayout = new javax.swing.GroupLayout(dobPanel);
        dobPanel.setLayout(dobPanelLayout);
        dobPanelLayout.setHorizontalGroup(
            dobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dobPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dobField, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        dobPanelLayout.setVerticalGroup(
            dobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dobPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(dobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel)
                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputPanel.add(dobPanel);

        agePanel.setBackground(new java.awt.Color(34, 43, 53));
        agePanel.setForeground(new java.awt.Color(242, 242, 242));

        ageLabel.setBackground(new java.awt.Color(60, 63, 66));
        ageLabel.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(242, 242, 242));
        ageLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ageLabel.setText("  Age:");

        ageField.setBackground(new java.awt.Color(72, 75, 80));
        ageField.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        ageField.setForeground(new java.awt.Color(242, 242, 242));
        ageField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agePanelLayout = new javax.swing.GroupLayout(agePanel);
        agePanel.setLayout(agePanelLayout);
        agePanelLayout.setHorizontalGroup(
            agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageField, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        agePanelLayout.setVerticalGroup(
            agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageLabel)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputPanel.add(agePanel);

        addressPanel.setBackground(new java.awt.Color(34, 43, 53));
        addressPanel.setForeground(new java.awt.Color(242, 242, 242));

        countryLabel.setBackground(new java.awt.Color(60, 63, 66));
        countryLabel.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        countryLabel.setForeground(new java.awt.Color(242, 242, 242));
        countryLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countryLabel.setText("  Address:");

        addressArea.setColumns(20);
        addressArea.setRows(5);
        addressPane.setViewportView(addressArea);

        javax.swing.GroupLayout addressPanelLayout = new javax.swing.GroupLayout(addressPanel);
        addressPanel.setLayout(addressPanelLayout);
        addressPanelLayout.setHorizontalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(countryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressPane, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        addressPanelLayout.setVerticalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(countryLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
        );

        inputPanel.add(addressPanel);

        usernamePanel.setBackground(new java.awt.Color(34, 43, 53));
        usernamePanel.setForeground(new java.awt.Color(242, 242, 242));

        usernameLabel.setBackground(new java.awt.Color(60, 63, 66));
        usernameLabel.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(242, 242, 242));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel.setText("  Username:");

        useridField.setBackground(new java.awt.Color(72, 75, 80));
        useridField.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        useridField.setForeground(new java.awt.Color(242, 242, 242));
        useridField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        useridField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
        usernamePanel.setLayout(usernamePanelLayout);
        usernamePanelLayout.setHorizontalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(useridField, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        usernamePanelLayout.setVerticalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(useridField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputPanel.add(usernamePanel);

        passwordPanel.setBackground(new java.awt.Color(34, 43, 53));
        passwordPanel.setForeground(new java.awt.Color(242, 242, 242));

        passwordLabel.setBackground(new java.awt.Color(60, 63, 66));
        passwordLabel.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(242, 242, 242));
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passwordLabel.setText("  Password:");

        passw.setBackground(new java.awt.Color(72, 75, 80));
        passw.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        passw.setForeground(new java.awt.Color(242, 242, 242));
        passw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passw, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputPanel.add(passwordPanel);

        confirmPwdPanel.setBackground(new java.awt.Color(34, 43, 53));
        confirmPwdPanel.setForeground(new java.awt.Color(242, 242, 242));

        confirmPwdLabel.setBackground(new java.awt.Color(60, 63, 66));
        confirmPwdLabel.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        confirmPwdLabel.setForeground(new java.awt.Color(242, 242, 242));
        confirmPwdLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        confirmPwdLabel.setText("  Confirm Password:");

        cpassw.setBackground(new java.awt.Color(72, 75, 80));
        cpassw.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        cpassw.setForeground(new java.awt.Color(242, 242, 242));
        cpassw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpasswActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmPwdPanelLayout = new javax.swing.GroupLayout(confirmPwdPanel);
        confirmPwdPanel.setLayout(confirmPwdPanelLayout);
        confirmPwdPanelLayout.setHorizontalGroup(
            confirmPwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmPwdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirmPwdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpassw, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        confirmPwdPanelLayout.setVerticalGroup(
            confirmPwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmPwdPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(confirmPwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpassw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPwdLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputPanel.add(confirmPwdPanel);

        schoolPanel.setBackground(new java.awt.Color(34, 43, 53));
        schoolPanel.setForeground(new java.awt.Color(242, 242, 242));

        countryLabel1.setBackground(new java.awt.Color(60, 63, 66));
        countryLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        countryLabel1.setForeground(new java.awt.Color(242, 242, 242));
        countryLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countryLabel1.setText("  University / School:");

        school.setBackground(new java.awt.Color(72, 75, 80));
        school.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        school.setForeground(new java.awt.Color(242, 242, 242));
        school.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        school.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout schoolPanelLayout = new javax.swing.GroupLayout(schoolPanel);
        schoolPanel.setLayout(schoolPanelLayout);
        schoolPanelLayout.setHorizontalGroup(
            schoolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schoolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(countryLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(school, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        schoolPanelLayout.setVerticalGroup(
            schoolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schoolPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(schoolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(school, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputPanel.add(schoolPanel);

        boardPanel.setBackground(new java.awt.Color(34, 43, 53));
        boardPanel.setForeground(new java.awt.Color(242, 242, 242));

        countryLabel2.setBackground(new java.awt.Color(60, 63, 66));
        countryLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        countryLabel2.setForeground(new java.awt.Color(242, 242, 242));
        countryLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countryLabel2.setText("  Board / Affilatiion:");

        board.setBackground(new java.awt.Color(72, 75, 80));
        board.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        board.setForeground(new java.awt.Color(242, 242, 242));
        board.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        board.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(countryLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(board, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputPanel.add(boardPanel);

        btnPanel.setBackground(new java.awt.Color(34, 43, 53));
        btnPanel.setForeground(new java.awt.Color(242, 242, 242));

        signUpBtn.setBackground(new java.awt.Color(60, 63, 66));
        signUpBtn.setForeground(new java.awt.Color(242, 242, 242));
        signUpBtn.setMaximumSize(new java.awt.Dimension(155, 30));
        signUpBtn.setMinimumSize(new java.awt.Dimension(155, 30));
        signUpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signUpBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signUpBtnMouseReleased(evt);
            }
        });

        signUpLabel.setBackground(new java.awt.Color(242, 242, 242));
        signUpLabel.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(242, 242, 242));
        signUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpLabel.setText("Sign Up");

        javax.swing.GroupLayout signUpBtnLayout = new javax.swing.GroupLayout(signUpBtn);
        signUpBtn.setLayout(signUpBtnLayout);
        signUpBtnLayout.setHorizontalGroup(
            signUpBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpBtnLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(signUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        signUpBtnLayout.setVerticalGroup(
            signUpBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpBtnLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(signUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        btnPanel.add(signUpBtn);

        optionPanel.setBackground(new java.awt.Color(34, 43, 53));
        optionPanel.setForeground(new java.awt.Color(242, 242, 242));

        loginPrompt.setBackground(new java.awt.Color(60, 63, 66));
        loginPrompt.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        loginPrompt.setForeground(new java.awt.Color(242, 242, 242));
        loginPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginPrompt.setText("Already have an account?");
        loginPrompt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginPromptMouseClicked(evt);
            }
        });
        optionPanel.add(loginPrompt);

        r2loginBtn.setBackground(new java.awt.Color(60, 63, 66));
        r2loginBtn.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        r2loginBtn.setForeground(new java.awt.Color(104, 181, 248));
        r2loginBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r2loginBtn.setText("Login");
        r2loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r2loginBtnMouseClicked(evt);
            }
        });
        optionPanel.add(r2loginBtn);

        footerPanel.setBackground(new java.awt.Color(34, 43, 53));
        footerPanel.setForeground(new java.awt.Color(242, 242, 242));

        Disclaimer.setBackground(new java.awt.Color(60, 63, 66));
        Disclaimer.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        Disclaimer.setForeground(new java.awt.Color(242, 242, 242));
        Disclaimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Disclaimer.setText("Abhishek Singh @ 21MIS1096");
        footerPanel.add(Disclaimer);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void dobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobFieldActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void notToSayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notToSayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notToSayActionPerformed

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    private void useridFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridFieldActionPerformed

    private void passwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwActionPerformed

    private void cpasswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpasswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpasswActionPerformed

    private void signUpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtnMouseClicked
        String name1 = nameField.getText();
        String name = name1.replace("'", ".Apos.");
        String age1 = ageField.getText();
        String age = age1.replace("'", ".Apos.");
        String dob = dobField.getText();
        String add1 = addressArea.getText();
        String add = add1.replace("'", ".Apos.");
        String brd1 = board.getText();
        String brd = brd1.replace("'", ".Apos.");        
        String sch1 = school.getText();
        String sch = sch1.replace("'", ".Apos."); 
        String uid = useridField.getText();
        String pwd = String.valueOf(passw.getPassword());
        String cpwd = String.valueOf(cpassw.getPassword());
        String gen = "";
        
        if (male.isSelected()) {
            gen = "Male";
        } else if (female.isSelected()) {
            gen = "Female";
        }
        if (name.equals("") || age.equals("") || dob.equals("") || add.equals("") || brd.equals("") || uid.equals("") || sch.equals("") || pwd.equals("") || cpwd.equals("") || gen.equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter All Values");
            return;
        }
        if(!pwd.equals(cpwd)){
            JOptionPane.showMessageDialog(null, "Password didn't match!");
            return;
        }

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","root");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT uid from LOGIN");
            int d = 0;
            while (rs.next()) {
                String id = rs.getString(1);
                if (id.equals(uid)) {
                    JOptionPane.showMessageDialog(null, "This user id already exists");
                    d = 1;
                }
            }
            if (d == 0) {
                String query = "INSERT INTO Login values('" + name + "','" + age + "','" + dob + "','" + gen + "','" + add + "','" + brd + "','" + sch + "','" + uid + "','" + pwd + "')";
                int i = st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Registration Succesfull");
                Quiz_Login f = new Quiz_Login();
                f.setVisible(true);
                this.dispose();
            }
            con.close();
            st.close();
            rs.close();
        } catch (SQLDataException e) {
            JOptionPane.showMessageDialog(null, "Please enter DOB in YYYY-MM-DD format");
        } catch (Exception e) {
            System.out.println(e);
        }
        

    }//GEN-LAST:event_signUpBtnMouseClicked

    private void signUpBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtnMouseEntered
        signUpBtn.setBackground(new java.awt.Color(26, 28, 29));
    }//GEN-LAST:event_signUpBtnMouseEntered

    private void signUpBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtnMouseExited
        signUpBtn.setBackground(new java.awt.Color(60, 63, 66));
    }//GEN-LAST:event_signUpBtnMouseExited

    private void signUpBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtnMousePressed
        signUpBtn.setBackground(new java.awt.Color(17, 18, 19));
    }//GEN-LAST:event_signUpBtnMousePressed

    private void signUpBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtnMouseReleased
        signUpBtn.setBackground(new java.awt.Color(60, 63, 66));
    }//GEN-LAST:event_signUpBtnMouseReleased

    private void r2loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r2loginBtnMouseClicked
        Quiz_Login f = new Quiz_Login();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_r2loginBtnMouseClicked

    private void loginPromptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginPromptMouseClicked
        Quiz_Login f = new Quiz_Login();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginPromptMouseClicked

    private void schoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolActionPerformed

    private void boardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz_Reg_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz_Reg_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz_Reg_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz_Reg_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz_Reg_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Disclaimer;
    private javax.swing.JTextArea addressArea;
    private javax.swing.JScrollPane addressPane;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JPanel agePanel;
    private javax.swing.JTextField board;
    private javax.swing.JPanel boardPanel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel confirmPwdLabel;
    private javax.swing.JPanel confirmPwdPanel;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JLabel countryLabel1;
    private javax.swing.JLabel countryLabel2;
    public javax.swing.JPasswordField cpassw;
    private javax.swing.JTextField dobField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JPanel dobPanel;
    private javax.swing.JRadioButton female;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel loginPrompt;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JRadioButton notToSay;
    private javax.swing.JPanel optionPanel;
    public javax.swing.JPasswordField passw;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JLabel r2loginBtn;
    private javax.swing.JTextField school;
    private javax.swing.JPanel schoolPanel;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JPanel sexPanel;
    private javax.swing.JPanel signUpBtn;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    public javax.swing.JTextField useridField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
